version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:9.3.11-ce.0
    container_name: gitlab
    ports: 
      - "8080:80"
      - "443:443"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
